service: poc-serverless-sqs

provider:
  name: aws
  profile: aws-serverless
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-067b9bb40a240e42c
    subnetIds:
      - subnet-0c19620347ff05c33
  stage: ${opt:stage, 'dev'}
  runtime: nodejs20.x
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
  timeout: 20

plugins:
  - serverless-offline

package:
  individually: true

# The name of your layer in the CloudFormation template will be your layer name TitleCased (without spaces) and have LambdaLayer appended to the end
# For a layer named "Test", use "!Ref TestLambdaLayer"
layers:
  node:
    description: A layer with node_modules for production environment and database certificates
    path: poc-serverless-sqs-layer
    package:
      # see project /docs/markdown/how-to-deploy.md to details as how to generate the aws-lambda-layer.zip file
      artifact: aws-lambda-layer/poc-serverless-sqs-layer.zip

functions:
  producer:
    package:
      include:
        - dist/apps/producer/lambda.js
      exclude:
        - ./**
    handler: dist/apps/producer/lambda.handler
    layers:
      - !Ref NodeLambdaLayer
    events:
      - http:
          method: POST
          path: /message

  consumer:
    package:
      include:
        - dist/apps/consumer/lambda.js
      exclude:
        - ./**
    handler: dist/apps/consumer/lambda.handler
    layers:
      - !Ref NodeLambdaLayer
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:841162678852:PocServerlessQueue
          batchSize: 2
          maximumBatchingWindow: 60 # seconds
          maximumConcurrency: 2
